//Image dictionary
const Images = {
  logo: require("../Images/logo.png"),
  head1: require("../Images/head1.png"),
  user1: require("../Images/1.jpg"),
  user2: require("../Images/2.jpg"),
  user3: require("../Images/3.jpg"),
  user4: require("../Images/4.jpg"),
  user5: require("../Images/5.jpg"),
  user6: require("../Images/6.jpg"),
  user7: require("../Images/7.jpg"),
  user8: require("../Images/8.jpg"),
  profile: require("../Images/profile.png"),
  stock1: require("../Images/stock1.jpg"),
  stock2: require("../Images/stock2.jpg"),
  stock3: require("../Images/stock3.jpg"),
  stock4: require("../Images/stock4.jpg"),
  stock5: require("../Images/stock5.jpg"),
  stock6: require("../Images/stock6.jpg"),
  stock7: require("../Images/stock7.jpg"),
  stock8: require("../Images/stock8.jpg"),
  stock9: require("../Images/stock9.jpg"),
  stock10: require("../Images/stock10.jpg"),
  stock11: require("../Images/stock11.jpg"),
  stock12: require("../Images/stock12.jpg"),
  stock13: require("../Images/stock13.jpg"),
  stock14: require("../Images/stock14.jpg"),
  stock15: require("../Images/stock15.jpg"),
  stock16: require("../Images/stock16.jpg"),
  stock17: require("../Images/stock17.jpg"),
  stock18: require("../Images/stock18.jpg"),
  stock19: require("../Images/stock19.jpg"),
  stock20: require("../Images/stock20.jpg"),
  stock21: require("../Images/stock21.jpg"),
  stock22: require("../Images/stock22.jpg"),
  stock23: require("../Images/stock23.jpg"),
  stock24: require("../Images/stock24.jpg"),
  stock25: require("../Images/stock25.jpg"),
  stock26: require("../Images/stock26.jpg"),
  stock27: require("../Images/stock27.jpg"),
  stock28: require("../Images/stock28.jpg"),
  stock29: require("../Images/stock29.jpg"),
  stock30: require("../Images/stock30.jpg"),
  stockedit: require("../Images/stockedit.jpg")
};

export default Images;

//Just the stock images
export function retrieveStockImages() {
  return [
    Images.stock1,
    Images.stock2,
    Images.stock3,
    Images.stock4,
    Images.stock5,
    Images.stock6,
    Images.stock7,
    Images.stock8,
    Images.stock9,
    Images.stock10,
    Images.stock11,
    Images.stock12,
    Images.stock13,
    Images.stock14,
    Images.stock15,
    Images.stock16,
    Images.stock17,
    Images.stock18,
    Images.stock19,
    Images.stock20,
    Images.stock21,
    Images.stock22,
    Images.stock23,
    Images.stock24,
    Images.stock25,
    Images.stock26,
    Images.stock27,
    Images.stock28,
    Images.stock29,
    Images.stock30
  ];
}
